interface Bank {
    id: number;
    name: string;
    slug: string;
    code: string;
    longcode: string;
    gateway: string;
    pay_with_bank: boolean;
    supports_transfer: boolean;
    active: boolean;
    country: string;
    currency: string;
    type: string;
    is_deleted: boolean;
    createdAt: string;
    updatedAt: string;
}

interface BanksResponse {
    status: boolean;
    message: string;
    data: Bank[];
}


export const banksData: BanksResponse = {
    "status": true,
    "message": "Banks retrieved",
    "data": [
        {
            "id": 1,
            "name": "Access Bank",
            "slug": "access-bank",
            "code": "044",
            "longcode": "044150149",
            "gateway": "emandate",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2020-02-18T08:06:44.000Z"
        },
        {
            "id": 3,
            "name": "Access Bank (Diamond)",
            "slug": "access-bank-diamond",
            "code": "063",
            "longcode": "063150162",
            "gateway": "emandate",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2020-02-18T08:06:48.000Z"
        },
        {
            "id": 300,
            "name": "Airtel Smartcash PSB",
            "slug": "airtel-smartcash-psb-ng",
            "code": "120004",
            "longcode": "120004",
            "gateway": "",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2022-05-30T14:03:00.000Z",
            "updatedAt": "2022-05-31T06:58:22.000Z"
        },
        {
            "id": 27,
            "name": "ALAT by WEMA",
            "slug": "alat-by-wema",
            "code": "035A",
            "longcode": "035150103",
            "gateway": "emandate",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2017-11-15T12:21:31.000Z",
            "updatedAt": "2022-05-31T15:54:34.000Z"
        },
        {
            "id": 692,
            "name": "CASHCONNECT MFB",
            "slug": "cashconnect-mfb-ng",
            "code": "865",
            "longcode": "865",
            "gateway": "",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2023-04-05T14:29:19.000Z",
            "updatedAt": "2023-04-05T14:29:19.000Z"
        },
        {
            "id": 2,
            "name": "Citibank Nigeria",
            "slug": "citibank-nigeria",
            "code": "023",
            "longcode": "023150005",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2020-02-18T20:24:02.000Z"
        },
        {
            "id": 755,
            "name": "CITYCODE MORTAGE BANK",
            "slug": "citycode-mortage-bank-ng",
            "code": "070027",
            "longcode": "070027",
            "gateway": "",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2023-12-30T06:16:39.000Z",
            "updatedAt": "2023-12-30T06:16:39.000Z"
        },
        {
            "id": 4,
            "name": "Ecobank Nigeria",
            "slug": "ecobank-nigeria",
            "code": "050",
            "longcode": "050150010",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2020-02-18T20:23:53.000Z"
        },
        {
            "id": 677,
            "name": "Fairmoney Microfinance Bank",
            "slug": "fairmoney-microfinance-bank-ng",
            "code": "51318",
            "longcode": "",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2022-11-15T12:33:47.000Z",
            "updatedAt": "2022-11-15T12:37:44.000Z"
        },
        {
            "id": 6,
            "name": "Fidelity Bank",
            "slug": "fidelity-bank",
            "code": "070",
            "longcode": "070150003",
            "gateway": "emandate",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2021-08-27T09:15:29.000Z"
        },
        {
            "id": 7,
            "name": "First Bank of Nigeria",
            "slug": "first-bank-of-nigeria",
            "code": "011",
            "longcode": "011151003",
            "gateway": "ibank",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2021-03-25T14:22:52.000Z"
        },
        {
            "id": 8,
            "name": "First City Monument Bank",
            "slug": "first-city-monument-bank",
            "code": "214",
            "longcode": "214150018",
            "gateway": "emandate",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2020-02-18T08:06:46.000Z"
        },
        {
            "id": 682,
            "name": "FirstTrust Mortgage Bank Nigeria",
            "slug": "firsttrust-mortgage-bank-nigeria-ng",
            "code": "413",
            "longcode": "",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2023-02-17T12:12:37.000Z",
            "updatedAt": "2023-06-15T16:21:12.000Z"
        },
        {
            "id": 70,
            "name": "Globus Bank",
            "slug": "globus-bank",
            "code": "00103",
            "longcode": "103015001",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2020-02-11T15:38:57.000Z",
            "updatedAt": "2020-02-11T15:38:57.000Z"
        },
        {
            "id": 183,
            "name": "GoMoney",
            "slug": "gomoney",
            "code": "100022",
            "longcode": "",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2021-08-04T11:49:46.000Z",
            "updatedAt": "2021-11-12T13:32:14.000Z"
        },
        {
            "id": 9,
            "name": "Guaranty Trust Bank",
            "slug": "guaranty-trust-bank",
            "code": "058",
            "longcode": "058152036",
            "gateway": "ibank",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2024-11-14T12:30:43.000Z"
        },
        {
            "id": 22,
            "name": "Jaiz Bank",
            "slug": "jaiz-bank",
            "code": "301",
            "longcode": "301080020",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-10-10T17:26:29.000Z",
            "updatedAt": "2016-10-10T17:26:29.000Z"
        },
        {
            "id": 11,
            "name": "Keystone Bank",
            "slug": "keystone-bank",
            "code": "082",
            "longcode": "082150017",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2020-02-18T20:23:45.000Z"
        },
        {
            "id": 67,
            "name": "Kuda Bank",
            "slug": "kuda-bank",
            "code": "50211",
            "longcode": "",
            "gateway": "digitalbankmandate",
            "pay_with_bank": true,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2019-11-15T17:06:54.000Z",
            "updatedAt": "2024-10-29T10:56:03.000Z"
        },
        {
            "id": 688,
            "name": "Moniepoint MFB",
            "slug": "moniepoint-mfb-ng",
            "code": "50515",
            "longcode": "null",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2023-03-20T12:53:58.000Z",
            "updatedAt": "2023-03-20T12:53:58.000Z"
        },
        {
            "id": 171,
            "name": "OPay Digital Services Limited (OPay)",
            "slug": "paycom",
            "code": "999992",
            "longcode": "",
            "gateway": "ibank",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2020-11-24T10:20:45.000Z",
            "updatedAt": "2024-10-29T10:56:03.000Z"
        },
        {
            "id": 185,
            "name": "Paga",
            "slug": "paga",
            "code": "100002",
            "longcode": "",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2021-08-31T08:10:00.000Z",
            "updatedAt": "2021-08-31T08:10:00.000Z"
        },
        {
            "id": 169,
            "name": "PalmPay",
            "slug": "palmpay",
            "code": "999991",
            "longcode": "",
            "gateway": "ibank",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2020-11-24T09:58:37.000Z",
            "updatedAt": "2024-10-22T10:43:42.000Z"
        },
        {
            "id": 629,
            "name": "Paystack-Titan",
            "slug": "titan-paystack",
            "code": "100039",
            "longcode": "",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2022-09-02T08:51:15.000Z",
            "updatedAt": "2024-03-26T14:31:05.000Z"
        },
        {
            "id": 770,
            "name": "Pocket App",
            "slug": "pocket",
            "code": "00716",
            "longcode": "00716",
            "gateway": "digitalbankmandate",
            "pay_with_bank": false,
            "supports_transfer": false,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2024-01-18T16:56:20.000Z",
            "updatedAt": "2024-10-29T10:56:03.000Z"
        },
        {
            "id": 13,
            "name": "Polaris Bank",
            "slug": "polaris-bank",
            "code": "076",
            "longcode": "076151006",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2016-07-14T10:04:29.000Z"
        },
        {
            "id": 25,
            "name": "Providus Bank",
            "slug": "providus-bank",
            "code": "101",
            "longcode": "",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2017-03-27T16:09:29.000Z",
            "updatedAt": "2021-02-09T17:50:06.000Z"
        },
        {
            "id": 14,
            "name": "Stanbic IBTC Bank",
            "slug": "stanbic-ibtc-bank",
            "code": "221",
            "longcode": "221159522",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2020-02-18T20:24:17.000Z"
        },
        {
            "id": 15,
            "name": "Standard Chartered Bank",
            "slug": "standard-chartered-bank",
            "code": "068",
            "longcode": "068150015",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2020-02-18T20:23:40.000Z"
        },
        {
            "id": 16,
            "name": "Sterling Bank",
            "slug": "sterling-bank",
            "code": "232",
            "longcode": "232150016",
            "gateway": "emandate",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2022-05-27T08:56:01.000Z"
        },
        {
            "id": 68,
            "name": "TAJ Bank",
            "slug": "taj-bank",
            "code": "302",
            "longcode": "",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2020-01-20T11:20:32.000Z",
            "updatedAt": "2020-01-20T11:20:32.000Z"
        },
        {
            "id": 17,
            "name": "Union Bank of Nigeria",
            "slug": "union-bank-of-nigeria",
            "code": "032",
            "longcode": "032080474",
            "gateway": "emandate",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2020-02-18T20:22:54.000Z"
        },
        {
            "id": 18,
            "name": "United Bank For Africa",
            "slug": "united-bank-for-africa",
            "code": "033",
            "longcode": "033153513",
            "gateway": "emandate",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2022-03-09T10:28:57.000Z"
        },
        {
            "id": 19,
            "name": "Unity Bank",
            "slug": "unity-bank",
            "code": "215",
            "longcode": "215154097",
            "gateway": "emandate",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2019-07-22T12:44:02.000Z"
        },
        {
            "id": 20,
            "name": "Wema Bank",
            "slug": "wema-bank",
            "code": "035",
            "longcode": "035150103",
            "gateway": "null",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2021-02-09T17:49:59.000Z"
        },
        {
            "id": 21,
            "name": "Zenith Bank",
            "slug": "zenith-bank",
            "code": "057",
            "longcode": "057150013",
            "gateway": "emandate",
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Nigeria",
            "currency": "NGN",
            "type": "nuban",
            "is_deleted": false,
            "createdAt": "2016-07-14T10:04:29.000Z",
            "updatedAt": "2023-09-26T17:09:43.000Z"
        }
    ]
}

export default banksData;